### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. 

### ISSUE THREAD

**Issue by Onetwo31** [hugocen/freqtrade-gym#25]
Hi, thanks for your work. A long time ago I worked about IA and trading, but never found a way to incorporate it too fractured.
I have this error despite I followed your guideline, please could you help me?
_____________________________________________________________________________________________________
(.env) (base) onetwo31@onetwo31-VirtualBox:~/Freqtrade_ia/freqtrade$ python rllib_example.py
Traceback (most recent call last):
  File "rllib_example.py", line 6, in <module>
    from freqtradegym import TradingEnv
  File "/home/onetwo31/Freqtrade_ia/freqtrade/freqtradegym.py", line 12, in <module>
    import talib.abstract as ta
  File "/home/onetwo31/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 52, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by Charlie-Root** [comment]
Remove and reinstall fixed it

`rm -rf .env/lib/python3.8/site-packages/numpy*

pip install --force-reinstall --no-deps numpy==1.22.0`

**Comment by Onetwo31** [comment]
Thanks to reply !
