### ISSUE TITLE
Problem while executing python deep_rl.py command

### ISSUE THREAD

**Issue by AhmedSakrr** [hugocen/freqtrade-gym#26]
>> python deep_rl.py
Traceback (most recent call last):
  File "deep_rl.py", line 7, in <module>
    from freqtradegym import TradingEnv
  File "/home/ubuntu/freqtrade/freqtradegym.py", line 16, in <module>
    from freqtrade.configuration import (TimeRange, remove_credentials,
ImportError: cannot import name 'remove_credentials' from 'freqtrade.configuration' (/home/ubuntu/freqtrade/freqtrade/configuration/__init__.py)
(.env) root@freqtrade2:/home/ubuntu/freqtrade# python3 deep_rl.py
Traceback (most recent call last):
  File "deep_rl.py", line 7, in <module>
    from freqtradegym import TradingEnv
  File "/home/ubuntu/freqtrade/freqtradegym.py", line 16, in <module>
    from freqtrade.configuration import (TimeRange, remove_credentials,
ImportError: cannot import name 'remove_credentials' from 'freqtrade.configuration' (/home/ubuntu/freqtrade/freqtrade/configuration/__init__.py)

**Comment by evo11x** [comment]
Did you found a solution for this error?

**Comment by jbk95** [comment]
It can work without importing remove_credentials.

**Comment by jcnance1** [comment]
Did anyone get this to work with this error ImportError: cannot import name 'remove_credentials' .
I'm getting the same thing

**Comment by mojito228** [comment]
> 

you can just delete 'remove_credentials' from freqtradegym, but this project is a little bit useless, due to python updates

**Comment by jcnance1** [comment]
ah that's sad, is it worth trying to revert to python 3.6? any idea if this project will be updated.

**Comment by mojito228** [comment]
> ah that's sad, is it worth trying to revert to python 3.6? any idea if this project will be updated.

No, cause you need numpy=1.22, which is supported only buy python3.8, otherwise you will have some errors
